### ISSUE TITLE
ext: t3extensions_widget for Frontend

### ISSUE THREAD

**Issue by typo3ua** [schams-net/t3extensions_widget#1]
Hello!

Maybe do you have `ext:t3extensions_widget` for Frontend, something like this https://t3extensions.org/?

Thanks!

**Comment by schams-net** [comment]
`EXT:t3extensions_widget` is a widget for the TYPO3 dashboard in the backend. If you want to process/output extension data for the frontend, you could retrieve the JSON data from `api.t3extensions.org` (remote API call) or access the extension list in your local instance directly (DB table `tx_extensionmanager_domain_model_extension`). There is also a Scheduler task that lets you update the list automatically.
