### ISSUE TITLE
Typo3 11.x compatibility

### ISSUE THREAD

**Issue by schrej-zz** [schams-net/t3extensions_widget#4]
Hi,
can we expect a version, that's compatible with 11.x?

**Comment by schams-net** [comment]
Thanks for reaching out. The TYPO3 v11 LTS compatibility was not even on my radar. Luckily, this update was a no-brainer and I just released [version 1.2.0](https://github.com/schams-net/t3extensions_widget/releases/tag/v1.2.0) of the extension which works in v10 and v11.
